name: treemap_ui
version: 0.3.0
description: A treemap user interface component for web applications
author: Uwe Sommerlatt <uwe.sommerlatt@gmail.com>
homepage: https://github.com/usommerl/treemap_ui
dependencies:
  browser: ">=0.6.3+1"
dev_dependencies:
  unittest: any
