name: treemap_ui
version: 0.3.3
description: A treemap user interface component for web applications
author: Uwe Sommerlatt <uwe.sommerlatt@gmail.com>
homepage: https://github.com/usommerl/treemap_ui
environment:
  sdk: ">=0.8.10+6 <2.0.0"
dependencies:
  browser: ">=0.6.3+1 <0.10.0"
dev_dependencies:
  unittest: ">=0.9.0 <0.10.0"
